// Generated by: npx supabase gen types typescript --project-id <your-project-id> > src/lib/supabase/types.ts
// Run this after applying migrations to replace this manual stub with fully-generated types.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      project_members: {
        Row: {
          project_id: string
          user_id: string
          added_at: string
        }
        Insert: {
          project_id: string
          user_id: string
          added_at?: string
        }
        Update: {
          project_id?: string
          user_id?: string
          added_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'project_members_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          }
        ]
      }
      user_profiles: {
        Row: {
          id: string
          role: 'admin' | 'analyst'
          full_name: string | null
          created_at: string
        }
        Insert: {
          id: string
          role?: 'admin' | 'analyst'
          full_name?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          role?: 'admin' | 'analyst'
          full_name?: string | null
          created_at?: string
        }
        Relationships: []
      }
      projects: {
        Row: {
          id: string
          name: string
          owner_id: string | null
          created_at: string
          platforms: string[]
          schedule_frequency: 'paused' | 'daily' | 'twice_daily' | 'four_times_daily' | 'weekly'
          brand_positioning: string | null
          alignment_check_mode: 'off' | 'manual' | 'auto'
        }
        Insert: {
          id?: string
          name: string
          owner_id?: string | null
          created_at?: string
          platforms?: string[]
          schedule_frequency?: 'paused' | 'daily' | 'twice_daily' | 'four_times_daily' | 'weekly'
          brand_positioning?: string | null
          alignment_check_mode?: 'off' | 'manual' | 'auto'
        }
        Update: {
          id?: string
          name?: string
          owner_id?: string | null
          created_at?: string
          platforms?: string[]
          schedule_frequency?: 'paused' | 'daily' | 'twice_daily' | 'four_times_daily' | 'weekly'
          brand_positioning?: string | null
          alignment_check_mode?: 'off' | 'manual' | 'auto'
        }
        Relationships: []
      }
      run_brand_alignment: {
        Row: {
          id: string
          run_id: string
          status: 'pending' | 'checking' | 'done' | 'failed'
          overall_verdict: 'aligned' | 'contradicted' | 'mixed' | 'unchecked' | null
          brand_brief_snapshot: string | null
          claims: Json
          error_message: string | null
          checked_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          run_id: string
          status?: 'pending' | 'checking' | 'done' | 'failed'
          overall_verdict?: 'aligned' | 'contradicted' | 'mixed' | 'unchecked' | null
          brand_brief_snapshot?: string | null
          claims?: Json
          error_message?: string | null
          checked_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          run_id?: string
          status?: 'pending' | 'checking' | 'done' | 'failed'
          overall_verdict?: 'aligned' | 'contradicted' | 'mixed' | 'unchecked' | null
          brand_brief_snapshot?: string | null
          claims?: Json
          error_message?: string | null
          checked_at?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'run_brand_alignment_run_id_fkey'
            columns: ['run_id']
            isOneToOne: true
            referencedRelation: 'runs'
            referencedColumns: ['id']
          }
        ]
      }
      brands: {
        Row: {
          id: string
          project_id: string
          name: string
          domain: string
          is_primary: boolean
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          name: string
          domain: string
          is_primary?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          name?: string
          domain?: string
          is_primary?: boolean
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'brands_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          }
        ]
      }
      competitors: {
        Row: {
          id: string
          project_id: string
          name: string
          domain: string
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          name: string
          domain: string
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          name?: string
          domain?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'competitors_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          }
        ]
      }
      prompts: {
        Row: {
          id: string
          project_id: string
          prompt_text: string
          volume: number
          priority: 'low' | 'medium' | 'high'
          is_active: boolean
          is_branded: boolean
          intent: 'informational' | 'commercial' | 'transactional'
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          prompt_text: string
          volume?: number
          priority?: 'low' | 'medium' | 'high'
          is_active?: boolean
          is_branded?: boolean
          intent?: 'informational' | 'commercial' | 'transactional'
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          prompt_text?: string
          volume?: number
          priority?: 'low' | 'medium' | 'high'
          is_active?: boolean
          is_branded?: boolean
          intent?: 'informational' | 'commercial' | 'transactional'
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'prompts_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          }
        ]
      }
      runs: {
        Row: {
          id: string
          prompt_id: string
          platform: 'chatgpt' | 'gemini'
          model_name: string | null
          run_date: string
          raw_response: string | null
          status: 'pending' | 'running' | 'success' | 'failed'
          error_message: string | null
          cost_usd: number | null
          created_at: string
        }
        Insert: {
          id?: string
          prompt_id: string
          platform: 'chatgpt' | 'gemini'
          model_name?: string | null
          run_date?: string
          raw_response?: string | null
          status?: 'pending' | 'running' | 'success' | 'failed'
          error_message?: string | null
          cost_usd?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          prompt_id?: string
          platform?: 'chatgpt' | 'gemini'
          model_name?: string | null
          run_date?: string
          raw_response?: string | null
          status?: 'pending' | 'running' | 'success' | 'failed'
          error_message?: string | null
          cost_usd?: number | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'runs_prompt_id_fkey'
            columns: ['prompt_id']
            isOneToOne: false
            referencedRelation: 'prompts'
            referencedColumns: ['id']
          }
        ]
      }
      mentions: {
        Row: {
          id: string
          run_id: string
          brand_id: string | null
          position: number | null
          sentiment: 'positive' | 'neutral' | 'negative' | null
          mentioned: boolean
          snippet: string | null
          mention_type: 'top_choice' | 'recommended' | 'mentioned_only' | null
          created_at: string
        }
        Insert: {
          id?: string
          run_id: string
          brand_id?: string | null
          position?: number | null
          sentiment?: 'positive' | 'neutral' | 'negative' | null
          mentioned?: boolean
          snippet?: string | null
          mention_type?: 'top_choice' | 'recommended' | 'mentioned_only' | null
          created_at?: string
        }
        Update: {
          id?: string
          run_id?: string
          brand_id?: string | null
          position?: number | null
          sentiment?: 'positive' | 'neutral' | 'negative' | null
          mentioned?: boolean
          snippet?: string | null
          mention_type?: 'top_choice' | 'recommended' | 'mentioned_only' | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'mentions_run_id_fkey'
            columns: ['run_id']
            isOneToOne: false
            referencedRelation: 'runs'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'mentions_brand_id_fkey'
            columns: ['brand_id']
            isOneToOne: false
            referencedRelation: 'brands'
            referencedColumns: ['id']
          }
        ]
      }
      citations: {
        Row: {
          id: string
          run_id: string
          domain: string
          url: string
          title: string | null
          snippet: string | null
          brand_id: string | null
          competitor_id: string | null
          position: number | null
          created_at: string
        }
        Insert: {
          id?: string
          run_id: string
          domain: string
          url: string
          title?: string | null
          snippet?: string | null
          brand_id?: string | null
          competitor_id?: string | null
          position?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          run_id?: string
          domain?: string
          url?: string
          title?: string | null
          snippet?: string | null
          brand_id?: string | null
          competitor_id?: string | null
          position?: number | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'citations_run_id_fkey'
            columns: ['run_id']
            isOneToOne: false
            referencedRelation: 'runs'
            referencedColumns: ['id']
          }
        ]
      }
      visibility_scores: {
        Row: {
          id: string
          project_id: string
          brand_id: string | null
          date: string
          platform: string
          mention_score: number | null
          position_score: number | null
          citation_score: number | null
          sentiment_score: number | null
          total_score: number | null
          prompt_count: number | null
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          brand_id?: string | null
          date: string
          platform: string
          mention_score?: number | null
          position_score?: number | null
          citation_score?: number | null
          sentiment_score?: number | null
          total_score?: number | null
          prompt_count?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          brand_id?: string | null
          date?: string
          platform?: string
          mention_score?: number | null
          position_score?: number | null
          citation_score?: number | null
          sentiment_score?: number | null
          total_score?: number | null
          prompt_count?: number | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'visibility_scores_project_id_fkey'
            columns: ['project_id']
            isOneToOne: false
            referencedRelation: 'projects'
            referencedColumns: ['id']
          }
        ]
      }
    }
    Views: Record<string, never>
    Functions: {
      compute_visibility_score: {
        Args: {
          p_project_id: string
          p_brand_id: string
          p_date: string
          p_platform: string
        }
        Returns: number
      }
      get_top_cited_domains: {
        Args: {
          p_project_id: string
          p_platform?: string
          p_date_from?: string
          p_date_to?: string
          p_limit?: number
        }
        Returns: Array<{
          domain: string
          citation_count: number
          run_count: number
          brand_name: string | null
          competitor_name: string | null
          last_seen: string
        }>
      }
      get_top_cited_urls: {
        Args: {
          p_project_id: string
          p_domain?: string
          p_platform?: string
          p_limit?: number
        }
        Returns: Array<{
          url: string
          domain: string
          title: string | null
          citation_count: number
          brand_name: string | null
          competitor_name: string | null
          last_seen: string
        }>
      }
      get_mention_rate: {
        Args: { p_project_id: string; p_date: string; p_brand_id?: string }
        Returns: number
      }
      get_avg_position: {
        Args: { p_project_id: string; p_date: string; p_brand_id?: string }
        Returns: number
      }
      get_sentiment_breakdown: {
        Args: { p_project_id: string; p_date: string; p_brand_id?: string }
        Returns: Json
      }
      get_geo_outreach_opportunities: {
        Args: {
          p_project_id: string
        }
        Returns: Array<{
          domain: string
          competitor_citations: number
          competitors_cited: string
          prompts_count: number
          sample_url: string
          sample_prompt: string
        }>
      }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
